### ISSUE TITLE
It seems like sloppyGlobals not working

### ISSUE THREAD

**Issue by Jack-Works** [Agoric/realms-shim#43] opened 2019-09-09 04:08 UTC
![image](https://user-images.githubusercontent.com/5390719/64502758-7c440400-d2fa-11e9-976d-039b23d1770a.png)

`sloppyGlobals` just won't work

**Comment by michaelfig** [comment] 2019-09-09 14:56
`sloppyGlobals` would require something like:
```js
a.evaluate('new Function("a = 1")`)();
```

They're called "sloppy" because it's approximately equal to how assignments to unreferenced global variables work in sloppy mode.  However, the code is still actually in strict mode, so a top-level `Function` gets `undefined` as its `this`.

Can you give that a try and LMK how it works for you?

Thanks for the report!

**Comment by Jack-Works** [comment] 2019-09-09 15:01
I understand. But new Function("this.x = y") or new Function("return this") is also a common pattern to assign to the global or get the globalThis.

**Comment by Jack-Works** [comment] 2019-09-09 15:02
I supported this binding to globalThis in #17

**Comment by michaelfig** [comment] 2019-09-10 17:12
Okay, #17 is something I haven't yet wrapped my head around.  My understanding is that it probably cannot be merged as-is (yet).

Sorry this is taking so long.  I will do a more detailed review with suggested changes, once I get some time.

**Comment by Jack-Works** [comment] 2019-09-11 01:16
You can cherry pick some commits from #17

**Comment by michaelfig** [comment] 2019-09-14 05:35
I will when I get some time.  If you want to expedite this, you can rework the code by taking @erights suggestions into account.

**Comment by erights** [comment] 2019-10-25 20:00
The `sloppyGlobals` flag itself is ***working as intended***. The only remaining question identified in the thread above is already the separately filed issue #17. So closing this one.

**Closed by erights** 2019-10-25 20:00 UTC
